// Homepage featured catalog. The first four products are shown in the
// "Featured products" strip on index.html, and the data mirrors shop.html
// so cart items added from /index resolve to the same products in /shop.
window.PRODUCTS = [
  {id:8, cat:"plushies",    name:"Custom Character Plushie",           price:849,  imgs:["insta_custom_orders.jpg","custom_plushie.jpg","plushie_custom_q.jpg"], desc:"Made-to-order flowers, booties, plushies, bags, rakhis and character pieces."},
  {id:3, cat:"plushies",    name:"Winnie the Pooh Plushie",            price:1499, imgs:["insta_pooh.jpg","pooh.png"], desc:"Beloved Winnie the Pooh in golden yellow with his iconic red top."},
  {id:20,cat:"plushies",    name:"Plushie Gift Set",                   price:2499, imgs:["plushies_collage.jpg","mini_plushies.png"], desc:"A curated gift set of handmade crochet plushies — perfect as a birthday, baby shower or anniversary gift."},
  {id:9, cat:"coasters",    name:"Sunflower Pot Holder",               price:649,  imgs:["insta_sunflower_coaster.jpg","sunflower-coaster.png","sunflower_flower.png","sunflower.png"], desc:"A handcrocheted sunflower coaster or pot holder — keeps your table safe under cups, mugs and warm dishes. A cheerful handmade piece available in custom colours."},
  {id:10,cat:"coasters",    name:"Mandala Centre Mat - 14-17 inches",  price:849,  imgs:["insta_mandala_mat.jpg","mandala_centre_mat.jpg"], desc:"Large handcrocheted mandala used as a centrepiece, tablemat or mandir/pooja space decoration. Made to order in any colour and size."},
  {id:7, cat:"plushies",    name:"Mini Plushies - Bunny, Bear & Chick", price:1399, imgs:["mini_plushies.png","plushie_mini_q.jpg"], desc:"Sweet trio of mini amigurumi - white bunny, caramel bear and yellow chick with rosy cheeks and safety eyes."},
  {id:22,cat:"flowers",     name:"Crochet Rose Bunch",                 price:549,  imgs:["bag_rose.jpg","insta_golden_bloom.jpg"], desc:"Handcrocheted roses in soft pink and red — beautiful as a bouquet, hair clip or decor piece."},
  {id:12,cat:"flowers",     name:"Crochet Daisy",                      price:349,  imgs:["daisy_flower.png","daisy.png"], desc:"White daisy with raised golden centre. Wear as a brooch or hair clip, or use as home decor."},
  {id:1, cat:"booties",     name:"Pink Ruffle Booties & Bow Headband", price:849,  imgs:["insta_booties.jpg","booties_ruffle.jpg"], desc:"Soft pink booties with white ruffle trim and a matching pink bow headband."},
  {id:18,cat:"booties",     name:"Pink Basket-Weave Booties",          price:849,  imgs:["booties_pink_basket.jpg","booties_ruffle.jpg"], desc:"Sweet pink basket-weave pattern booties with a delicate crochet border — perfect for gifting a new arrival."},
  {id:2, cat:"booties",     name:"Classic Lace-Up Booties",            price:749,  imgs:["insta_booties_twins.jpg","booties_classic.jpg"], desc:"Cream booties with jute lace-up ties on a wooden slice."},
  {id:19,cat:"booties",     name:"Lace-Up Wooden Booties",             price:799,  imgs:["booties_lace_wood.jpg","booties_classic.jpg"], desc:"Cosy booties displayed on a wooden prop with neat lace-up ties — available in cream, white and custom colours."},
  {id:4, cat:"plushies",    name:"Minion Plushie (Stuart)",            price:1199, imgs:["minion.png"], desc:"Everyone's favourite yellow troublemaker, crocheted with blue overalls and a single grey goggle."},
  {id:5, cat:"plushies",    name:"Santa Plushie",                      price:1999, imgs:["santa_plushie.jpg","plushie_santa_q.jpg"], desc:"Jolly Santa in red with fluffy white beard, black belt and boots."},
  {id:6, cat:"plushies",    name:"Shark Plushie",                      price:1199, imgs:["shark_plushie.png","plushie_shark_q.jpg"], desc:"Chubby blue-grey shark with rosy cheeks, safety eyes and a red-stitched smile."},
  {id:11,cat:"coasters",    name:"Leaf & Heart Coasters",              price:649,  imgs:["coasters_leaf_heart.jpg","coasters_mats.png"], desc:"Green monstera leaf coaster and pink heart coaster, sweet, practical and perfect as a set."},
  {id:23,cat:"coasters",    name:"Round Mandala Table Mat",             price:799,  imgs:["mandala_centre_mat.jpg","coasters_mats.png"], desc:"Round handcrocheted mandala mat — beautiful as a centrepiece, tablemat or mandir decoration. Custom colours and sizes available."},
  {id:13,cat:"flowers",     name:"Golden Tangled Bloom",               price:649,  imgs:["insta_golden_bloom.jpg","sunflower.png","sunflower_flower.png"], desc:"A twist of sunlight and spellwork, handcrafted as a warm golden bloom."},
  {id:14,cat:"bags",        name:"Rose Drawstring Bag",                price:1999, imgs:["bag_rose.jpg","bag_rose_drawstring.jpg"], desc:"Cream crochet drawstring bag with pink and red roses and green leaves on the front."},
  {id:15,cat:"bags",        name:"Sunflower Round Sling Bag",          price:2499, imgs:["bag_sunflower.jpg","bag_sunflower_sling.jpg"], desc:"Round brown sling bag with a full sunflower on the front and a slim rope strap."},
  {id:16,cat:"accessories", name:"Bow Hair Headband",                  price:549,  imgs:["insta_kids_accessory.jpg","bow_headband.png"], desc:"Handmade crochet kids accessory details, soft and available in all colours."},
  {id:17,cat:"rakhis",      name:"Custom Crochet Rakhi Set",           price:649,  imgs:["rakhis_main.jpg","rakhis_marble.jpg","rakhi_bow.jpg","rakhis_trio.jpg"], desc:"Handmade rakhis - heart, evil eye, rose, name charm, daisy, moon, bow and more."},
  {id:21,cat:"rakhis",      name:"Rakhi Collection Overview",          price:649,  imgs:["rakhis_overview.jpg","rakhis_main.jpg","rakhis_trio.jpg"], desc:"Explore the full range of handmade crochet rakhis — hearts, evil eyes, roses, name charms, daisies and more."}
];
